[Colors]
accent=#912c2c
background=#000000
background_fullscreen=#000000
folderview=#191319
folderview_topbar=#191319
icons=#d8d8d8
overlay=#191319
overlay_text=#d8d8d8
scrollbar=#6e2a2a
text=#d8d8d8
tid=5
widget=#191319
widget_border=#191319
