general {
    hide_cursor = true
}

animations {
    animation = fadeIn, 1, 6, default
    animation = fadeOut, 1, 5, default
}

background {
    path = ~/Pictures/Wallpapers/Red Lily Spider by AssassinWarrior.jpg
    blur_passes = 3
}

label {
    text = $TIME
    color = rgb(216, 216, 216)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 75
}

label {
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgb(216, 216, 216)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -25
}

input-field {
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.24
    dots_spacing = 0.21
    outer_color = rgb(8c2d2a)
    inner_color = rgba(25, 19, 25, 0.75)
    rounding = 5
    font_color = rgb(216, 216, 216)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##d8d8d8">Input password</span></i>
    check_color = rgb(a66a29)
    fail_color = rgb(8c2d2a)
    position = 0, -95
}

