general {
    hide_cursor = true
}

animations {
    animation = fadeIn, 1, 6, default
    animation = fadeOut, 1, 5, default
}

background {
    path = ~/Pictures/Wallpapers/Red Lily Spider by AssassinWarrior.jpg
    blur_passes = 3
}

input-field {
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(621E1E)
    inner_color = rgba(25, 19, 25, 0.75)
    rounding = 5
    font_color = rgb(216, 216, 216)
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i><span foreground="##d8d8d8">Input password</span></i>
    hide_input = false
    position = 0, -100
    halign = center
    valign = center
}

label {
    text = $TIME
    color = rgb(216, 216, 216)
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, -350
    halign = center
    valign = top
}

label {
    text = cmd[update:60000] echo "$(date +"%A, %B %d")"
    color = rgb(216, 216, 216)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -25
    halign = center
    valign = center
}

