alang=rus,ru,ukr,uk
ao=pipewire
audio-file-auto=fuzzy
audio-file-paths=**
autocreate-playlist=same
cscale=lanczos
dscale=lanczos
hr-seek=yes
hwdec=auto
osc=no
osd-font=JetBrainsMono Nerd Font
osd-on-seek=no
profile=high-quality
scale=lanczos
screenshot-directory=~/Pictures/Screenshots
screenshot-format=png
screenshot-template="%F - [%P] (%#01n)"
slang=rus,ru,ukr,uk
sub-auto=fuzzy
sub-file-paths=**
tone-mapping=bt.2446a
video-output-levels=full
vo=gpu-next
volume-max=100

